name: Trigger GlueOps/github-actions-cleanup-redundant-cd-prs

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  call-close-old-prs-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Run Cleanup
        uses: GlueOps/github-actions-cleanup-redundant-cd-prs@v0.2.0
        with:
          pr_number: ${{ github.event.pull_request.number }}
          gh_token: ${{ secrets.GITHUB_TOKEN }}
